name: Run Stale PR Bot

on:
  schedule:
    # Runs every day at midnight UTC
    - cron: '0 0 * * *'
  # Allows manual triggering as well
  workflow_dispatch:

jobs:
  run-stale-pr-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t stale-pr-bot .

      - name: Run Docker Container
        run: docker run --rm \
          -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
          -e GITHUB_BASE_URL="${{ secrets.GITHUB_BASE_URL }}" \
          -e GITHUB_OWNER="${{ secrets.GITHUB_OWNER }}" \
          -e GITHUB_REPO="${{ secrets.GITHUB_REPO }}" \
          -e DAYS_INACTIVE="${{ secrets.DAYS_INACTIVE }}" \
          -e WARNING_PERIOD="${{ secrets.WARNING_PERIOD }}" \
          -e SMTP_SERVER="${{ secrets.SMTP_SERVER }}" \
          -e SMTP_PORT="${{ secrets.SMTP_PORT }}" \
          -e SMTP_USER="${{ secrets.SMTP_USER }}" \
          -e SMTP_PASSWORD="${{ secrets.SMTP_PASSWORD }}" \
          -e EMAIL_DOMAIN="${{ secrets.EMAIL_DOMAIN }}" \
          stale-pr-bot
